### ISSUE TITLE
Docu, examples

### ISSUE THREAD

**Issue by leros321** [fiveai/terraform-provider-freeipa#4]
We are using ipa server (Redhat IDM) and looking for user management solution.
Because, we are using terraform as IaC, we would like use this approach for user management (add, delete, modify, …)
But, there is no docu like https://github.com/fiveai/terraform-provider-xenserver .

**Is possible to write it?**

**Comment by graemedavidson** [comment]
> We are using ipa server (Redhat IDM) and looking for user management solution.
> Because, we are using terraform as IaC, we would like use this approach for user management (add, delete, modify, …)
> But, there is no docu like https://github.com/fiveai/terraform-provider-xenserver .
> 
> **Is possible to write it?**

Sorry for the delay, in PR now if you did still need though hoping you put it together yourself
